---
title: "Explore"
author: "Arielle Herman"
date: "11/25/2022"
output: html_document
---

```{r}
library(tidyverse)
mc <- haven::read_dta("data/GreenWinikMC.dta")

gw <- read_csv("data/green_winik_data.csv") %>%
  mutate(across(ends_with("date"), ~as.Date(., "%m/%d/%Y")))

md <- XML::xmlToList(XML::xmlParse("data/metadata.xml"))
str(md$Fragment$Variable)
str_which(unlist(md), "drug1")
unlist(md)[1300:1310]
str(md$Fragment$StudyUnit)
bind_rows()
purrr::reduce(md$Fragment$StudyUnit, bind_cols)
```
# dictionary

+ highestcharge: pwid - possession with intent to distribute, dist - charged with felony distribution, question: is pwid higher than dist?
+ felonycharges: number of felony charges (1-3), question: other charges are not listed?
+ gender: F, M, W? question: what is "W"? "woman"?

```{r}
gw %>% count(felonycharges, highestcharge) %>% arrange(desc(n))

gw %>% count(month = zoo::as.yearmon(pickupdate), race) %>% mutate(prop = n/sum(n)) %>%
  ggplot(aes(x = month, y = prop, color = race)) + geom_line() +
  ylab("Proportion of total observations\n") + xlab("pick up month") +
  ggthemes::theme_tufte(ticks = FALSE)
```
